application: shs1509-grc
version: 2 
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
